name: Zoz Node Simple
on:
  push
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Zoz Whoop Deploy
    runs-on: ubuntu-latest    

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::407767216233:role/github-actions-role
        aws-region: us-west-2
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1        
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: zoz-node
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f ./Dockerfile.simplenode -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"  
          