name: Zoz Node Simple
on:
  push
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Zoz Whoop Deploy
    runs-on: ubuntu-latest    

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::407767216233:role/github-actions-role
        aws-region: us-west-2
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1        
