name: AWS example workflow
on:
  push
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    name: Zoz Whoop
    runs-on: ubuntu-latest    
    env:
      AWS_DEFAULT_REGION: us-west-2

    steps:
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::407767216233:role/github-actions-role
        aws-region: us-west-2
    - name: Checkout
      uses: actions/checkout@v3